### ISSUE TITLE
NOTFOUND in all files types and format instead of lists

### ISSUE THREAD

**Issue by Hubbitus** [vakhov/fresh-proxy-list#2]
Hello.
First thank you for the proxies in the past.

No matter which format request, there are only one content - single word "NOTFOUND":

```bash
$ curl -s -L https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/http.txt
NOTFOUND
$ curl -s -L https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/proxylist.json
NOTFOUND
```

Some goes wrong?

**Comment by vakhov** [comment]
Hello!
Thank you for pointing out the issue. It turned out to be a problem with an external service, but it has been resolved now. Please try again, and let us know if everything works as expected.

**Comment by Hubbitus** [comment]
Now it works! Thank you!
